//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DM_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DM_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DM_en_US", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria required.
        /// </summary>
        internal static string ErrorMsgRuleCategory {
            get {
                return ResourceManager.GetString("ErrorMsgRuleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Of Business required..
        /// </summary>
        internal static string ErrorMsgRuleType {
            get {
                return ResourceManager.GetString("ErrorMsgRuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Creation.
        /// </summary>
        internal static string hdrRuleCreation {
            get {
                return ResourceManager.GetString("hdrRuleCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string lblDataType {
            get {
                return ResourceManager.GetString("lblDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string lblExample {
            get {
                return ResourceManager.GetString("lblExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include functions.
        /// </summary>
        internal static string lblIncludeFunctions {
            get {
                return ResourceManager.GetString("lblIncludeFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Roles.
        /// </summary>
        internal static string lblRole {
            get {
                return ResourceManager.GetString("lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Criteria.
        /// </summary>
        internal static string lblRuleCategory {
            get {
                return ResourceManager.GetString("lblRuleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string lblRulePriority {
            get {
                return ResourceManager.GetString("lblRulePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Of Business.
        /// </summary>
        internal static string lblRuleType {
            get {
                return ResourceManager.GetString("lblRuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Column.
        /// </summary>
        internal static string lblSelectColumn {
            get {
                return ResourceManager.GetString("lblSelectColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Table.
        /// </summary>
        internal static string lblSelectTable {
            get {
                return ResourceManager.GetString("lblSelectTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Rule.
        /// </summary>
        internal static string TabhdrCreateRule {
            get {
                return ResourceManager.GetString("TabhdrCreateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Defined Rule.
        /// </summary>
        internal static string TabhdrPreDefinedRule {
            get {
                return ResourceManager.GetString("TabhdrPreDefinedRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process and Updates.
        /// </summary>
        internal static string TabhdrProcessAndUpdate {
            get {
                return ResourceManager.GetString("TabhdrProcessAndUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Allocation.
        /// </summary>
        internal static string TabhdrRuleAllocation {
            get {
                return ResourceManager.GetString("TabhdrRuleAllocation", resourceCulture);
            }
        }
    }
}
