
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DM_DataModel
{

using System;
    
public partial class CMN_GET_ROLE_SP_Result1
{

    public long Role_ID { get; set; }

    public string Role_Name { get; set; }

    public string Role_Description { get; set; }

    public int Active_Flag { get; set; }

    public byte Sys_Admin { get; set; }

}

}
