
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DM_DataModel
{

using System;
    
public partial class PRC_TO_UPDATE_SOURCE_TABLE_QUERY_SP
{

    public string UpdateQuery { get; set; }

}

}
